import os
import time

s1 = ('#######    #      ###   ##   ##')
s2 = ('   #      # #    #   #  ##  ## ')
s3 = ('   #     #   #  #     # ## ##  ')
s4 = ('   #     #   #  #       ###    ')
s5 = ('   #     #####  #     # ## ##  ')
s6 = ('#  #    #     #  #   #  ##  ## ')
s7 = (' ##     #     #   ###   ##   ##')

for j in range(5) :
    os.system("cls")    
    print (s1)
    print (s2)
    print (s3)
    print (s4)
    print (s5)
    print (s6)
    print (s7)
    l1 = list(s1)
    l2 = list(s2)
    l3 = list(s3)
    l4 = list(s4)
    l5 = list(s5)
    l6 = list(s6)
    l7 = list(s7)
    l1.insert(0, "  ")
    l2.insert(0, "  ")
    l3.insert(0, "  ")
    l4.insert(0, "  ")
    l5.insert(0, "  ")
    l6.insert(0, "  ")
    l7.insert(0, "  ")
    s1 = "".join(l1)
    s2 = "".join(l2)
    s3 = "".join(l3)
    s4 = "".join(l4)
    s5 = "".join(l5)
    s6 = "".join(l6)
    s7 = "".join(l7)
    time.sleep(1)
    continue